title: Visom Global
description: "Bespoke Solutions to Bridge Technology & Innovation"
theme: jekyll-theme-hacker
author:
  name: "ViSom"
  email: "piya777vidi@gmail.com"
  url: "https://ViSomglobal.com"
baseurl: /

source: .
destination: ./_site
